### ISSUE TITLE
[Improvement] Bindings for control+left-click are super annoying

### ISSUE THREAD

**Issue by NyxCode** [archcraft-os/archcraft-dwm#10]
The bindings for CTRL+LeftClick are super annoying imho. Took me quite a bit to figure out while CTRL+LeftClick on links in my browser didn't open a new tab.

```
{ ClkClientWin,         ControlMask,    Button1,        dragmfact,      {0} },
{ ClkClientWin,         ControlMask,    Button3,        dragcfact,      {0} },
```
I'd advocate for removing these two bindings in `config.def.h` (345-345) or binding them to an other key/modifier

**Comment by dorianim** [comment]
I agree 100%!

**Comment by adi1090x** [comment]
Done!
