### ISSUE TITLE
[Bug] Passphrase prompt while connecting to wireless networks is broken

### ISSUE THREAD

**Issue by NyxCode** [archcraft-os/archcraft-dwm#11]
When connecting to wireless networks, the passphrase prompt is broken.  
For me, it only shows an empty modal. Typing in it has no effect.  
When pressing enter to confirm, it tries to connect, but I assume with an empty passphrase, so the connection fails.

![image](https://user-images.githubusercontent.com/20114928/180876785-26f3c1ea-f23a-4add-890c-8966e68c0143.png)

**Comment by NyxCode** [comment]
I've replaced it for now with `nmd` - not sure though what exactly is wrong with the the rofi `network_menu`.

**Comment by adi1090x** [comment]
Fixed
