### ISSUE TITLE
how to change the defaults applications in dwm

### ISSUE THREAD

**Issue by alavaelian** [archcraft-os/archcraft-dwm#12]
i want to reenplaze the default therminal and the default web browser in the   keyboard shortcuts and the default app to open a file

**Comment by NyxCode** [comment]
You can change the keybindings in `/opt/dwm_source/config.def.h`. For most of them, they delegate to scripts in `/usr/share/archcraft/dwm/bin/`

**Comment by alavaelian** [comment]
i do not need to recompile the file ? please tell me how if i need to do that

**Comment by NyxCode** [comment]
If you change `/opt/dwm_source/config.def.h`, yes, you have to recompile with `sudo make clean && sudo make install` and then restart with MOD+SHIFT+R

**Comment by alavaelian** [comment]
and to change the prefered apps ?
