### ISSUE TITLE
archcraft-dwm on another arch based distro/pure arch

### ISSUE THREAD

**Issue by oTerminal** [archcraft-os/archcraft-dwm#2]
Hello. I wanted archcraft-dwm on my different Arch install but I'm missing many things like rofi etc. May I know what all the dependencies are? Thanks!

**Comment by mateusdcc** [comment]
I have the same question, it would be fantastic if that was possible!

**Comment by ddiaz2380** [comment]
I think it would be even better if we could choose within the installation itself which desktop to use, be it bswpm, dwm, openbox or i3 because having bspwm and openbox already installed, then having to insert dwm doesn't make much sense.

**Comment by wrenfannin** [comment]
> Hello. I wanted archcraft-dwm on my different Arch install but I'm missing many things like rofi etc. May I know what all the dependencies are? Thanks!

Easiest thing to do is to find those other things on the archcraft github and copy over configs to your system

**Comment by adi1090x** [comment]
Build it manually on your Arch or whichever distro you use, use files from this repo.
