### ISSUE TITLE
st: 🐳 leads to crash

### ISSUE THREAD

**Issue by dorianim** [archcraft-os/archcraft-dwm#5]
Hey,

St crashes when there is the `🐳` character somewhere. Would be nice to get that fixed :)

**Comment by adi1090x** [comment]
Not here, Check your system locale. it needs to be in UTF-8 format.

![Screenshot_2024-04-04-18-10-50_3840x1080](https://github.com/archcraft-os/archcraft-dwm/assets/26059688/1f4e9989-8ebe-49dd-a4dc-a8703f3b9173)
