### ISSUE TITLE
[Bug] Bar language issue

### ISSUE THREAD

**Issue by cyl3x** [archcraft-os/archcraft-dwm#8]
Same as I mentioned here at the [main repo](https://github.com/archcraft-os/archcraft/issues/247).
Happenes in ```archcraft-dwm/shared/bin/dwmbar.sh``` in the ```memory``` function.
I really appreciate your work :)

**Comment by adi1090x** [comment]
Not a general issue.
Can simple be resolved by adding `export LANG=en_US.utf-8` in `/usr/share/archcraft/dwm/scripts/dwm_bar` script.
